language: php
php:
  - 5.4
before_install:
  - composer self-update
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
install:
  - ./test/create_working_copy.sh
  - cd test/working_copy
  - npm install -g grunt-cli
  - npm install -g mocha
script:
  - export PATH=$PATH:`pwd`/bin
  - grunt
  - grunt drush:liteinstall
  - grunt drush:runserver &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do sleep 0.2; done
  - grunt behat
  - mocha node_modules/grunt-drupal-tasks/test
